import Image from "next/image";

export default function AddingContext() {
  return (
    <div className="container-section lg:py-10 xl:py-10 flex flex-col gap-8 lg:pr-52 xl:pr-64 !pb-32">
      <div>
        <h1 className="font-semibold xl:text-4xl text-3xl">Creating Context for Data Agent</h1>
        <p className="mt-2">
          Context is the knowledge that you add to your data agent to help Analyst Zero understand your data better.
          This is optional but recommended step in making LLM stay grounded and more accurate. We have integrated AI at
          every step of adding context to help you setup as fast and easy as possible.
        </p>
      </div>

      <div>
        <h4 className="font-semibold text-2xl">Types of context</h4>
        <ol className="list-decimal list-inside mt-2 space-y-2">
          <li className="">
            <span className="font-semibold">Data Entity Metadata (IMPORTANT):</span> This is the metadata of the data
            entities (tables) you have in your database. This includes the table description, column description and
            foreign key descriptions for your data entities.
          </li>

          <li>
            <span className="font-semibold">Data Agent Metrics (IMPORTANT):</span> These are any metrics that you want
            to track for the data agent. It consists of a metric name, its abbreviation and description of the metric.
          </li>

          <li>
            <span className="font-semibold">Data Agent Metric Examples:</span> These are any examples queries that
            calculate the metric. It consists of a query and its explanation.
          </li>

          <li>
            <span className="font-semibold">Data Agent Examples:</span> These are any examples queries that contain the
            data entities that are included in the data agent. It consists of a query and its explanation. Though not that
            important, it helps LLM to understand the data entities and the context of the data agent in case you have
            not added any metrics or metric examples.
          </li>
        </ol>
      </div>

      {/* Step 1: Sign up and create an organisation */}
      <div className="flex flex-col gap-3">
        <h3 className="font-semibold text-2xl">1. Adding Data Entity Metadata</h3>
        <ol className="list-decimal list-inside mt-1 space-y-1">
          <p className="text-lg">Follow these steps to add data entity metadata:</p>
          <li>
            Go to <span className="font-semibold">Data Sources</span> from the sidebar and click on{" "}
            <span className="font-semibold">View Entities</span> for the data source you want to add metadata for.
          </li>
          <li>
            Here you will see all the data entities (tables) in the data source. If you haven&apos;t added metadata to
            any of the data entities, it will show &quot;No Description&quot; in red color.
          </li>
          <li>
            Click on <span className="font-semibold">Edit</span> button for the data entity to which you want add
            metadata.
          </li>
          <li>
            You can either add metadata yourself or click on <span className="font-semibold">Generate AI Metadata</span>{" "}
            button to generate it for you. This will automatically <span className="font-semibold">generate</span> and{" "}
            <span className="font-semibold">save</span> the metadata for the data entity.
          </li>
        </ol>
        <div className="p-2 border rounded-lg text-sm bg-blue-50">
          <span className="font-semibold">Note:</span> Remember to verify the metadata generated by AI and make any
          changes if required. For columns that require additional structure information (like JSON, or STRUCT), you
          need to manually add these details to the column description. For example, if you have a JSON column storing
          user preferences, you should add the structure of the JSON to the column description.
        </div>
        <Image
          src="/docs/context-data-entity-metadata.png"
          alt="Add data source"
          width={1000}
          height={1000}
          className="rounded-lg border shadow-md mt-3"
        />
      </div>

      {/* Step 2: Adding Data Agent Metrics */}
      <div className="mt-4 flex flex-col gap-3">
        <h3 className="font-semibold text-2xl">2. Adding Data Agent Metrics</h3>

        <ol className="list-decimal list-inside mt-1 space-y-1">
          <p className="text-lg font-medium">Follow these steps to add data agent metrics:</p>
          <li>
            Go to Data Agents from the sidebar and click on <span className="font-semibold">Add Metrics</span> button.
          </li>
          <li>
            Add the metric name, its abbreviation and explanation of the metric. You can use AI to generate the
            explanation by clicking on <span className="font-semibold">Generate AI Description</span> button. This wil
            open dialog where you need to select the Data Entities that are related to the metric.
          </li>
        </ol>
        <div className="p-2 border rounded-lg text-sm bg-blue-50">
          <span className="font-semibold">Note:</span> Remember to verify the explanation generated by AI before saving
          the metric.
        </div>
        <Image
          src="/docs/context-create-metric.png"
          alt="Sync data entities"
          width={1000}
          height={1000}
          className="rounded-lg border shadow-md mt-3"
        />
      </div>

      {/* Step 3: Adding Data Agent Metric Examples */}
      <div className="mt-4 flex flex-col gap-3">
        <h3 className="font-semibold text-2xl">3. Adding Data Agent Metric Examples</h3>

        <ol className="list-decimal list-inside mt-1 space-y-1">
          <p className="text-lg font-medium">Follow these steps to add data agent metrics:</p>
          <li>
            Go to Data Agents from the sidebar and click on <span className="font-semibold">View Metrics</span> button.
          </li>
          <li>
            This will open all the metrics you have added to the data agent. Click on{" "}
            <span className="font-semibold">Add Example</span> button for the metric you want to add an example for.
          </li>
          <li>
            Here you need to add the query and its explanation. You can use AI to generate the explanation for the query
            by clicking on <span className="font-semibold">Generate AI Explanation</span> button. Remember to verify the
            explanation generated by AI before saving the example.
          </li>
        </ol>

        <div className="p-2 border rounded-lg text-sm bg-blue-50">
          <span className="font-semibold">Note:</span> If you don&apos;t have any example queries for the metric, you
          can use <span className="font-semibold">SQL Playground</span> to generate them. In SQL Playground, select the
          Metric and its associated Data Entities and tell AI to generate query. Once generated, you can add the query
          here.
        </div>

        <Image
          src="/docs/context-create-metric-example.png"
          alt="Create data agent"
          width={1000}
          height={1000}
          className="rounded-lg border shadow-md mt-2"
        />
      </div>

      {/* Step 4: Adding Data Agent Examples */}
      <div className="mt-4 flex flex-col gap-3">
        <h3 className="font-semibold text-2xl">4. Adding Data Agent Examples</h3>

        <ol className="list-decimal list-inside mt-1 space-y-1">
          <p className="text-lg font-medium">Follow these steps to add data agent examples:</p>
          <li>
            Go to Data Agents from the sidebar and click on <span className="font-semibold">Add Example</span> button.
          </li>
          <li>
            Here you need to add the query and its explanation. You can use AI to generate the explanation by clicking
            on <span className="font-semibold">Generate AI Explanation</span>. Remember to verify the explanation
            generated by AI before saving the example.
          </li>
        </ol>

        <div className="p-2 border rounded-lg text-sm bg-blue-50">
          <span className="font-semibold">Note:</span> If you don&apos;t have any examples for the data agent, you can use{" "}
          <span className="font-semibold">SQL Playground</span> to generate them. In SQL Playground, select the
          associated Data Entities and tell AI to generate the query. Once generated, you can add the query here.
        </div>

        <Image
          src="/docs/context-create-example.png"
          alt="Create data agent"
          width={1000}
          height={1000}
          className="rounded-lg border shadow-md mt-2"
        />
      </div>
    </div>
  );
}
