"""Changed the usage feature to enum and added both as an option

Revision ID: 633b8a784109
Revises: 822b67e4c218
Create Date: 2024-12-08 22:14:43.842153

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "633b8a784109"
down_revision: Union[str, None] = "822b67e4c218"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "early_access_users",
        "usage_feature",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.Enum("SLACK_CHAT_FEATURE", "PLATFORM_FEATURE", "BOTH", name="earlyaccessuserusagefeature"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "early_access_users",
        "usage_feature",
        existing_type=sa.Enum("SLACK_CHAT_FEATURE", "PLATFORM_FEATURE", "BOTH", name="earlyaccessuserusagefeature"),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
