"""Added Created Date and Updated Date in early access users

Revision ID: 77f3c5e4996c
Revises: f11c37cbfac2
Create Date: 2024-12-06 18:09:07.539392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f3c5e4996c'
down_revision: Union[str, None] = 'f11c37cbfac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('early_access_users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('early_access_users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('early_access_users', 'updated_at')
    op.drop_column('early_access_users', 'created_at')
    # ### end Alembic commands ###
