"""Added Usage Type, Usage Feature, and Explanation

Revision ID: 822b67e4c218
Revises: 77f3c5e4996c
Create Date: 2024-12-08 21:43:41.865521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '822b67e4c218'
down_revision: Union[str, None] = '77f3c5e4996c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('early_access_users', sa.Column('usage_type', sa.Enum('TEAM_USE', 'PERSONAL_USE', name='earlyaccessuserusagetype'), nullable=True))
    op.add_column('early_access_users', sa.Column('usage_feature', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('early_access_users', sa.Column('explanation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('early_access_users', 'explanation')
    op.drop_column('early_access_users', 'usage_feature')
    op.drop_column('early_access_users', 'usage_type')
    # ### end Alembic commands ###
