"""Added sqlite to data source type

Revision ID: 84d6c71e8a2d
Revises: bbebf08917c2
Create Date: 2024-12-21 01:01:35.577628

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84d6c71e8a2d"
down_revision: Union[str, None] = "bbebf08917c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE datasourcetype ADD VALUE IF NOT EXISTS 'SQLITE' AFTER 'SNOWFLAKE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### Unfortunately, PostgreSQL doesn't support removing enum values ###
    pass
    # ### end Alembic commands ###
