"""Updated organisation models - 1

Revision ID: 851c6e4bc7f3
Revises: d9e50075e5f9
Create Date: 2024-12-11 17:23:21.671539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851c6e4bc7f3'
down_revision: Union[str, None] = 'd9e50075e5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation_usage_limits', sa.Column('daily_small_credit_limit', sa.Integer(), nullable=True))
    op.add_column('organisation_usage_limits', sa.Column('daily_large_credit_limit', sa.Integer(), nullable=True))
    op.add_column('organisation_usage_limits', sa.Column('monthly_small_credit_limit', sa.Integer(), nullable=True))
    op.add_column('organisation_usage_limits', sa.Column('monthly_large_credit_limit', sa.Integer(), nullable=True))
    op.drop_column('organisation_usage_limits', 'daily_small_playground_credit_limit')
    op.drop_column('organisation_usage_limits', 'monthly_small_playground_credit_limit')
    op.drop_column('organisation_usage_limits', 'monthly_large_playground_credit_limit')
    op.drop_column('organisation_usage_limits', 'daily_large_playground_credit_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation_usage_limits', sa.Column('daily_large_playground_credit_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('organisation_usage_limits', sa.Column('monthly_large_playground_credit_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('organisation_usage_limits', sa.Column('monthly_small_playground_credit_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('organisation_usage_limits', sa.Column('daily_small_playground_credit_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('organisation_usage_limits', 'monthly_large_credit_limit')
    op.drop_column('organisation_usage_limits', 'monthly_small_credit_limit')
    op.drop_column('organisation_usage_limits', 'daily_large_credit_limit')
    op.drop_column('organisation_usage_limits', 'daily_small_credit_limit')
    # ### end Alembic commands ###
