"""Updated organisation model daily and monthly credits - 1

Revision ID: bbebf08917c2
Revises: 851c6e4bc7f3
Create Date: 2024-12-12 21:46:57.512484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbebf08917c2'
down_revision: Union[str, None] = '851c6e4bc7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
