"""baseline

Revision ID: c1248723b062
Revises:
Create Date: 2024-11-17 01:59:04.688530

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c1248723b062"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
