"""Updated organisation models

Revision ID: d9e50075e5f9
Revises: 974c41ff4502
Create Date: 2024-12-11 17:19:47.227691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e50075e5f9'
down_revision: Union[str, None] = '974c41ff4502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_organisation_id_date', 'organisation_daily_usage', ['organisation_id', 'date'])
    op.create_unique_constraint(None, 'organisation_usage_limits', ['organisation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organisation_usage_limits', type_='unique')
    op.drop_constraint('unique_organisation_id_date', 'organisation_daily_usage', type_='unique')
    # ### end Alembic commands ###
