"""Added Example Questions Charter

Revision ID: f11c37cbfac2
Revises: c1248723b062
Create Date: 2024-11-24 18:20:58.856011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f11c37cbfac2'
down_revision: Union[str, None] = 'c1248723b062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charter', sa.Column('example_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charter', 'example_questions')
    # ### end Alembic commands ###
